[package]
name = "bevy_2d_animation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
ron = "0.8.1"
serde = "1.0.189"